name: Create and publish a Docker image

on:
  workflow_dispatch:
    inputs:
      powertunnel-release:
        type: string
        description: PowerTunnel release
        required: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate name
        run: |
          echo "NAME=${OWNER,,}/${REPO,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
          REPO: '${{ github.event.repository.name }}'
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm 
          push: true
          tags: ghcr.io/${{ env.NAME }}:${{ inputs.powertunnel-release }}
          build-args: POWER_TUNNEL_RELEASE=${{ inputs.powertunnel-release }}